### ISSUE TITLE
Cocoapods please

### ISSUE THREAD

**Issue by lfarah** [philackm/Scrollable-GraphView#1]
I'd be cool to also add Cocoapods support. I done this implementation myself last month for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by philackm** [comment]
I was thinking about doing this also. 

I also need to remove the deprecated language features of Swift 2 and replace them with the Swift 3 equivalents. I'll do this at the same time. Thank you for the links!

**Comment by thephatp** [comment]
+1 for Cocoapod support.

**Comment by philackm** [comment]
CocoaPods support should be fine now. Try "pod ScrollableGraphView" in your Podfile.
