### ISSUE TITLE
Number of labels in the x-axis

### ISSUE THREAD

**Issue by elavarasanFluke** [philackm/Scrollable-GraphView#10]
is it possible to reduce the number labels shown on the x-axis? When I have to show large number of points , label in the x-axis are overlapping. And I don't want large spacing between those points.

**Comment by philackm** [comment]
The logic for the x-axis is very simple, it just prints a label at the required position for **every** data point. The only options at the moment are font size, or to turn off the labels altogether. 

I'll add this to the TODO list but it won't be available for a while unfortunately.
