### ISSUE TITLE
CocoaPods doesn't work

### ISSUE THREAD

**Issue by diogenesvanzella** [philackm/Scrollable-GraphView#14]
Hi, I'm trying to use your Lib, but when I add " pod 'ScrollableGraphView' " to my Podfile, the following error occurs.. " Unable to find a specification for 'ScrollableGraphView' ". How can I solve this problem?

**Comment by philackm** [comment]
I just tested this here and I can't seem to replicate it, this was my output after running "pod update":

<img width="846" alt="screen shot 2016-06-05 at 5 32 51 am" src="https://cloud.githubusercontent.com/assets/2552214/15801646/296e5e40-2adf-11e6-9a91-2ef075fcc8e5.png">

My Podfile was simply:

```
use_frameworks!

target 'PodTest' do
    pod 'ScrollableGraphView'
end
```

Are you sure the spelling is correct and that there are no unwanted symbols in the Podfile?

Alternatively, this link (https://stackoverflow.com/questions/25913733/unable-to-find-a-specification-in-cocoapods) suggests running `pod setup` and then trying again.

**Comment by diogenesvanzella** [comment]
Thanks! When I update the error disappear, now is working!
