### ISSUE TITLE
Scroll after create Graph

### ISSUE THREAD

**Issue by llKoull** [philackm/Scrollable-GraphView#16]
Hello!

First of all I want to thank you about this awesome library! I'm using it in a new project and It's really smooth. I only have one question. Is it posible to automatically scroll to the end of the graph after it appears on the view?

Best regards!

**Comment by hdoria** [comment]
Same problem here.

**Comment by hdoria** [comment]
Just figured it out. You can change the scroll direction:

```swift
graphView.direction = ScrollableGraphViewDirection.RightToLeft
```

RightToLeft will automatically scroll to the end of the graph .

**Comment by llKoull** [comment]
Hi hdoria!

I tried this line of code but It doesn't work for me 😟

`let graphView = ScrollableGraphView(frame: CGRectMake(0.0, 0.0, self.frame.width, self.frame.height))
        graphView.topMargin = 80
        
        graphView.backgroundFillColor = UIColor.colorFromHex("#333333")
                
        graphView.lineWidth = 1
        graphView.lineColor = UIColor.colorFromHex("#777777")
        graphView.lineStyle = ScrollableGraphViewLineStyle.Smooth
        
        graphView.shouldFill = true
        graphView.fillType = ScrollableGraphViewFillType.Gradient
        graphView.fillColor = UIColor.colorFromHex("#555555")
        graphView.fillGradientType = ScrollableGraphViewGradientType.Linear
        graphView.fillGradientStartColor = UIColor.colorFromHex("#555555")
        graphView.fillGradientEndColor = UIColor.colorFromHex("#444444")
        
        graphView.dataPointSpacing = 80
        graphView.dataPointSize = 2
        graphView.dataPointFillColor = UIColor.whiteColor()
        
        graphView.referenceLineLabelFont = UIFont.boldSystemFontOfSize(8)
        graphView.referenceLineColor = UIColor.whiteColor().colorWithAlphaComponent(0.2)
        graphView.referenceLineLabelColor = UIColor.whiteColor()
        graphView.dataPointLabelColor = UIColor.whiteColor().colorWithAlphaComponent(0.5)
        
        graphView.shouldAnimateOnStartup = true
        graphView.shouldAdaptRange = true
        graphView.adaptAnimationType = .Elastic
        graphView.animationDuration = 1.5
        graphView.shouldRangeAlwaysStartAtZero = true
        
        self.graphView?.direction = .RightToLeft
        
        graphView.setData(values, withLabels: labels)
        self.graphContainerView.addSubview(graphView)`

**Comment by philackm** [comment]
@hdoria Yes! That property can be used to change which end of the graph it starts at.

@llKoull Try changing:

`self.graphView?.direction = .RightToLeft`

to

`self.graphView.direction = .RightToLeft`

I don't think you have declared graphView as an optional.

Otherwise I can't see any other major mistakes. Does it not start at the end of the graph even after changing the direction to .RightToLeft? (Note there is no scrolling animation for this property, it will just start at the end of the graph and the user will have to swipe to the left to see the start of the graph.)

**Comment by llKoull** [comment]
Hi @philackm !

I tried to use `self.graphView.direction = .RightToLeft` but xcode gives me an error and I cant compile. I also tried to declare it as ! and the i can compile but i get 

> unexpectedly found nil while unwrapping an Optional value

I always have to scroll from left to right no matters which direction i choose :O

Thanks for your help

**Comment by llKoull** [comment]
I finally got this working, It was my fault, I was using `self.grapView` and i should use `graphview` instead.

But now i've got another problem, The graph scroll, that's nice, but the graphic it's not filled with color It seems that only half part of the graphic is filled until i touch It (some lines and the Y-axis values are also hidden. If i touch the graph It fills up with the correct color).

I attach some pictures!

![1](https://cloud.githubusercontent.com/assets/5525265/15911933/2f77fa08-2dd2-11e6-81bd-5275a3912c5c.png)
![2](https://cloud.githubusercontent.com/assets/5525265/15911934/2fa543f0-2dd2-11e6-9d2e-c4032f110956.png)


Thanks and best regards!

**Comment by philackm** [comment]
Hmmm. Could you post the code you have to a GitHub gist (https://gist.github.com) and then post the link here? I'd like to try reproduce it and find what's causing the bug.

**Comment by llKoull** [comment]
I'm sorry, but i can't post all the code. Anyways, I can tell you what i've done.

I created a UICollectionView with a custom cell called GraphCollectionViewCell. This is the code of the custom cell:

`import UIKit
import ScrollableGraphView

class GraphCollectionViewCell: UICollectionViewCell {
    
    @IBOutlet weak var graphTitle: UILabel!
    @IBOutlet weak var graphContainerView: UIView!
    var graphView: ScrollableGraphView?
    
    required init(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)!
    }
    
    func initializeGraph(values: [Double], labels: [String])
    {
        let graphView = ScrollableGraphView(frame: CGRectMake(0.0, 0.0, self.frame.width, self.frame.height))
        graphView.topMargin = 80

        graphView.backgroundFillColor = UIColor.colorFromHex("#333333")
                
        graphView.lineWidth = 1
        graphView.lineColor = UIColor.colorFromHex("#777777")
        graphView.lineStyle = ScrollableGraphViewLineStyle.Smooth
        
        graphView.shouldFill = true
        graphView.fillType = ScrollableGraphViewFillType.Gradient
        graphView.fillColor = UIColor.colorFromHex("#555555")
        graphView.fillGradientType = ScrollableGraphViewGradientType.Linear
        graphView.fillGradientStartColor = UIColor.colorFromHex("#555555")
        graphView.fillGradientEndColor = UIColor.colorFromHex("#444444")
        
        graphView.dataPointSpacing = 80
        graphView.dataPointSize = 2
        graphView.dataPointFillColor = UIColor.whiteColor()
        
        graphView.referenceLineLabelFont = UIFont.boldSystemFontOfSize(8)
        graphView.referenceLineColor = UIColor.whiteColor().colorWithAlphaComponent(0.2)
        graphView.referenceLineLabelColor = UIColor.whiteColor()
        graphView.dataPointLabelColor = UIColor.whiteColor().colorWithAlphaComponent(0.5)
        
        graphView.shouldAnimateOnStartup = true
        graphView.shouldAdaptRange = true
        graphView.adaptAnimationType = .Elastic
        graphView.animationDuration = 1.5
        graphView.shouldRangeAlwaysStartAtZero = true
            
        graphView.setData(values, withLabels: labels)
        graphView.direction = .RightToLeft
        self.graphContainerView.addSubview(graphView)
    }
    
    // MARK: Setters
    
    
    
    // MARK: Getters
    
    
    
}
`

Then I initialize the cell in the main view using the function 

> func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell

with the following code:

`let cell = collectionView.dequeueReusableCellWithReuseIdentifier(identifier, forIndexPath: indexPath) as! GraphCollectionViewCell
            cell.initializeGraph(stepsArray, labels: labelsArray)
            return cell`

I think that I autolayout can be affecting to the view.

Thanks for your help!

**Comment by hdoria** [comment]
Same problem here. This only happens when using ScrollableGraphViewDirection.RightToLeft.

**Comment by philackm** [comment]
Okay I just pushed 1.1.1 to cocoapods.

@hdoria, @llKoull Can you please try that version and let me know if it is any better?

**Comment by llKoull** [comment]
Yeah! It's working perfect! ^_^

Thanks @philackm !!!
