### ISSUE TITLE
Deprecated Language Features

### ISSUE THREAD

**Issue by philackm** [philackm/Scrollable-GraphView#2]
Multiple language features will be removed in Swift 3. The deprecated language features must be replaced with the Swift 3 equivalents.

**Comment by thephatp** [comment]
+1 for this as well.

BTW, this is **beautiful**! I can't have so many warnings in the project I'm working on right now, but whenever you're able to update the warnings, I'm definitely planning on integrating your code here. THANK YOU for making something so slick! 👍
