### ISSUE TITLE
Animation resets if multiple calls are made

### ISSUE THREAD

**Issue by felix-dumit** [philackm/Scrollable-GraphView#20]
Hi,

First of all thanks for this awesome library!

I've been using it and sometimes the graph gets updated twice (usually with the same data), before the animation of the first calls finishes. And this causes the animation to abort and restart for the 2nd call. Which looks odd.

To test this include the following code in the `viewDidLoad` method of the example project:

```swift 
  dispatch_after(dispatch_time(DISPATCH_TIME_NOW, Int64(graphView.animationDuration * 0.5 * Double(NSEC_PER_SEC))), dispatch_get_main_queue()){
       self.graphView.setData(self.data, withLabels: self.labels)
 }
```

I think possible solutions would be:

1) Always start the 2nd animation at the current point each point is
2) If the 2nd call has the exact same data as the currently animating call, don't animate it.

**Comment by philackm** [comment]
Hi!

Thanks for this! 

I will have to implement number 1 in the future, but for now I've pushed a new version (1.1.2) which checks if you're setting the same data again and if so, ignores it.

Can you try it out and let me know if it fixes your problem?

**Comment by felix-dumit** [comment]
@philackm Yeah that fixes it, thanks for the quick reply!

**Comment by floriannagel** [comment]
I can back this up, i want to realise a simple WaveForm and it looks uncool, because the whole bar is refreshing again and again. Is there a solution? :/

**Comment by philackm** [comment]
Can you explain a little bit about what you mean by "a simple waveform"?

**Comment by floriannagel** [comment]
Something like this: https://developers.soundcloud.com/assets/posts/waveform_rendering_mask-2d44b706dd9171ec4bdb6720fa2c0fb1.png
But just with Bars going Up. Don't know if i can make it in both directions. Up und Down. Und i have an array which will be reloaded fast. So the animation just startet over and over

**Comment by philackm** [comment]
I'm still not entirely sure what you want to do.

You should be able to create a bar graph that looks like a waveform, here is an example of a sine wave:

![simulator screen shot jun 14 2016 12 43 08 pm](https://cloud.githubusercontent.com/assets/2552214/16029636/9506b530-322d-11e6-9c80-f60c4466dcba.png)

Are you trying to animate the waveform? As in, are you updating the array and then calling setData in very quick succession? 

If so, that isn't really supported and was not the idea of calling setData, however, you should be able to do it by turning off the startup animation (and by using the latest version in cocoapods, I had to make a change to make it work). Again, this isn't really supported though. (If it is indeed what you're trying to do.)

`graphView.shouldAnimateOnStartup = false`

I was able to animate a sine wave by turning that setting off and then calling setData very quickly.

![Sine Wave Animation](https://cloud.githubusercontent.com/assets/2552214/16029726/6f59acba-322e-11e6-933e-ede2fdcfa31a.gif)

**Comment by floriannagel** [comment]
Thank you :)

**Comment by shindonghyeok** [comment]
i also want to get a waveform... so you said you called setData very quickly, how can i do that??
