### ISSUE TITLE
Scroll to end on initial load

### ISSUE THREAD

**Issue by xcadaverx** [philackm/Scrollable-GraphView#33]
Is there a way to scroll to the end of the view after the animation is complete? or even before the animation starts?

**Comment by philackm** [comment]
There is no scrolling animation, but the the variable 'direction' can be used to decide which side of the graph to start at.

Possible values:

    ScrollableGraphViewDirection.LeftToRight
    ScrollableGraphViewDirection.RightToLeft

For example, if it is set to .RightToLeft, the graph will start on the "right hand side" of the graph and the user will have to scroll towards the left.
