### ISSUE TITLE
Swift 3 Version!

### ISSUE THREAD

**Issue by cocoaHari** [philackm/Scrollable-GraphView#39]
Can you please update it to support Swift 3?

**Comment by rafaelc0sta** [comment]
Did a barebones, working swift3 version.

https://github.com/philackm/Scrollable-GraphView/pull/45/

**Comment by sovannarithsok** [comment]
Please release a new version for swift 3 that you have fixed. Thanks

**Comment by rafaelc0sta** [comment]
@sovannarithsok Already released. It's on my fork, branch "swift3". Not on CocoaPods though (we'll have to wait for the #45 PR to be merged)

**Comment by dhf** [comment]
@sovannarithsok, cocoaHari better use this [PR #48](https://github.com/philackm/Scrollable-GraphView/pull/48) , by using the other one the datapoint are not all drawn correctly, additional PR #48 also contains the methods and enums renamed conforming to the new Swift 3 naming conventions from Apple

**Comment by philackm** [comment]
Solved by #48!
