### ISSUE TITLE
init(coder:) not implemented

### ISSUE THREAD

**Issue by thephatp** [philackm/Scrollable-GraphView#4]
Consider this a feature request rather than a bug. :)

It would be much more convenient to be able to connect directly to the GraphView from Interface Builder. Unfortunately, I have to create a container right now, because when I hook it up in IB, it tries to call the method that is not implemented yet: 

`    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
`

**Comment by Fudge0952** [comment]
I would say this is a bug because a larger portion of people are creating their views in interface builder.

**Comment by philackm** [comment]
This should get resolved when #8 does.

**Comment by guydaher** [comment]
@thephatp Maybe you can help me with problems about putting this GraphView in a container. I wrote the issue in SO http://stackoverflow.com/questions/37794369/container-view-not-satisfying-autolayout?noredirect=1#comment63057118_37794369
Would appreciate the help.

**Comment by filipealva** [comment]
@philackm Firstly congrats about this awesome project!

Would be nice to have #28 merged before #8. I imagine that a lot of users of Scrollable-GraphView are modifying the `init(coder:)` method just to use it from IB. Please, consider it 👍

**Comment by philackm** [comment]
Tested and everything seems okay! Merged it in! Thanks!
