### ISSUE TITLE
A Possible enhancement...

### ISSUE THREAD

**Issue by geogerar** [philackm/Scrollable-GraphView#44]
Hi,

Nice work indeed.
Can we have 2 line scrollable graph?
This will be a nice enhancement!

Thank you very much

George Gerardis

**Comment by geogerar** [comment]
If you give also, an example of using it in objective c that will be nice!

George

**Comment by philackm** [comment]
Thank you. Unfortunately I don't know much about Objective C, maybe someone else can help out with that?

As for the multi-line graph, that is the same as #41, which I will keep track of there.
