### ISSUE TITLE
Support set barColor with random color.

### ISSUE THREAD

**Issue by kilirushi** [philackm/Scrollable-GraphView#50]
Hi.
Your framework be very helpful. I have a issues need your support with set color barColor as photo bellow. You can help me?.
<img width="600" alt="68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d5043686172742f6d61737465722f73637265656e73686f74732f73696d706c6564657369676e5f6261726368617274332e706e67" src="https://cloud.githubusercontent.com/assets/17327812/19415541/5a489c16-939d-11e6-927d-dbcb371763e4.png">

**Comment by philackm** [comment]
This is the same as #25. It shouldn't be too hard to support a colour for each data point, I'll keep track of it in #25 though.
