### ISSUE TITLE
How can I Give the values to X-Axis and Y-Axis?

### ISSUE THREAD

**Issue by Nandulucky** [philackm/Scrollable-GraphView#61]
Hello, I'm using Scrollable-GraphView of DarkGraph. But I don't know to add the x-axis and y-axis values from my end I have dates in x-axis and float values in Y-axis in different arrays.
How can I give the 2 arrays to X-axis and Y-axis. Thanks!

**Comment by philackm** [comment]
The values on the y-axis reference lines are generated automatically depending on the settings provided. (See the README).

You provide the labels for each point on the x-axis, and then the corresponding value for that point.

```
let graphView = ScrollableGraphView(frame: someFrame)
let data: [Double] = [4, 8, 15, 16, 23, 42]
let labels = ["one", "two", "three", "four", "five", "six"]
graphView.setData(data, withLabels: labels)
```

Please check out the README, it has a bunch of examples. There is also the example project you can load into Xcode and play around with it.
