### ISSUE TITLE
Label on bar top

### ISSUE THREAD

**Issue by leonardosalles** [philackm/Scrollable-GraphView#63]
Hi,

For first, thanks for this awesome code.

At this time I am facing a problem with labels and my question is if there is a way to add a value on top of the bar, for example I have a bar of month January and at the bottom I want to add "January" label and on top of this bar I want to add "R$ 100,00" as a String, is this possible? If yes, please someone can explain how?

PS: Please label it as Question ;)

Thanks.

**Comment by philackm** [comment]
This currently isn't possible, however I have created a branch with some changes which shows a quick hack to the code to make it happen. Check out the [diff here](https://github.com/philackm/Scrollable-GraphView/commit/25e0b8708eb0f52c7fe82e1c546c35a89939c999) on the branch toplabels. It would require a bit more work but it is a good start.

![screen shot 2017-01-05 at 11 31 35 am](https://cloud.githubusercontent.com/assets/2552214/21664551/5c771ae8-d33b-11e6-8ebe-2e8fa4323f4c.png)

I don't have the time to integrate it properly, at the moment the major thing it is lacking is the integration into the animation system, which would require updating the position of each label in topLabelPool.activeLabels during the animation. It would also need a boolean setting to enable/disable it.

**Comment by leonardosalles** [comment]
Great work, I will gonna work on that branch and will try to make the rest of the work also I will send a pull request when work has done ;)

**Comment by leonardosalles** [comment]
@philackm did you included a property to set top labels or you just get the bar value and set it as top label?

**Comment by philackm** [comment]
I haven't done anything except adding another labelpool that creates a label at the y-value of the bar. (Actually all data points, it will show labels above all points on all graph types at the moment.)

**Comment by philackm** [comment]
Additionally, lines 1259 and 1260 are where I calculate the intermediate bar (graph data point) values during animations. The labels would also have to be updated to those locations somehow.

**Comment by leonardosalles** [comment]
I will close this issue, your branch solved my problem, because I don't use animations, if you want to add it to animation system please go ahead but this is not the requirement of my issue. Finally, thanks for you code again.

**Comment by yakupad** [comment]
Thanks @philackm It makes a lot of work 👍 🥇 💯
