### ISSUE TITLE
Feature Request: Comments on variables

### ISSUE THREAD

**Issue by Fudge0952** [philackm/Scrollable-GraphView#7]
It would be really nice to have some `///` comments before each variable so we know what each one is doing without having to reverse engineer your code 😄

**Comment by philackm** [comment]
I tried to keep the variable names as descriptive as possible. It appears I could have done better!

Which variables in particular are you having trouble with? Each public variable has a description (a couple even have images!) in the README file here: https://github.com/philackm/Scrollable-GraphView#Customisation

**Comment by philackm** [comment]
Ah, okay. I just checked it out. The triple slash comments appear in the IDE when accessing the variables!

I'll update them so it's easier to use!

**Comment by Fudge0952** [comment]
😊 The variables are relatively self explanatory but if would be nice to have the description pop up when I type the variable 😊. If you want an easy way to comment your variables and functions I would strongly recommend [VVDocumenter](https://github.com/onevcat/VVDocumenter-Xcode). I have no connection with them but I use it all the time now.
